import { cleanup, fireEvent, render, screen } from '@testing-library/react';
import { afterEach, describe, expect, it } from 'vitest';
import attemptFixture from '../../../../fixtures/ui/attempt.json';
import neighboursFixture from '../../../../fixtures/ui/attempt-neighbours.json';
import eventsFixture from '../../../../fixtures/ui/events.json';
import neighbourEventsFixture from '../../../../fixtures/ui/events-neighbours.json';
import personasFixture from '../../../../fixtures/ui/personas.json';
import sessionFixture from '../../../../fixtures/ui/session.json';
import villageFixture from '../../../../fixtures/ui/village.json';
import type { SessionDetail } from '../api/iteration';
import type { AttemptDetail, DomainEvent, PersonasPayload, VillagePayload } from '../api/types';
import { usePlayback } from '../scene/playback';
import { sentenceFor } from '../selectors/story';
import { dayChangeLines } from '../selectors/words';
import CompareScreen, { type CompareDecisions } from './CompareScreen';
import EvaluationsScreen from './EvaluationsScreen';
import ObserveScreen from './ObserveScreen';
import RecordingsScreen, { madeBy, stoppedEarly } from './RecordingsScreen';

// Mounting the two data-heavy screens against real API payloads built from the
// SYNTHETIC village (fixtures/ui/, regenerated by scripts/gen_ui_fixtures.py).
//
// Synthetic on purpose: these files are committed, and the source-derived
// registry lives in the gitignored local-data/ precisely so that real place
// names, ages and jobs never enter the repository. The payload *shapes* are
// identical, which is what the screens are being tested against.
//
// The point is not pixels. It is that a screen which throws on real data, or
// which quietly prints "undefined" or an internal event name where a sentence
// belongs, is otherwise invisible: `tsc` cannot see it and this repository has
// no browser in CI. So each assertion below is a claim the screen makes about
// the run - never a restatement of a stylesheet.

const village = villageFixture as unknown as VillagePayload;
const detail = attemptFixture as unknown as AttemptDetail;
const events = (eventsFixture as { events: DomainEvent[] }).events;
/** The same day under 가까운 이웃 우선, where the refusal table actually fires. */
const neighbours = neighboursFixture as unknown as AttemptDetail;
const neighbourEvents = (neighbourEventsFixture as { events: DomainEvent[] }).events;
const personas = personasFixture as unknown as PersonasPayload;
const session = sessionFixture as unknown as SessionDetail;

const noop = () => {};
const decisions: CompareDecisions = {
  onConfirmChangeSet: noop,
  onSaveResearcherChangeSet: async () => null,
  onDeclineChanges: noop,
  onOpenFieldSheet: noop,
};

/**
 * Open a hint and read what it says.
 *
 * The screens' careful sentences - what a number is not, which two things the
 * measure mixes, why a blank is not a zero - now sit behind a "?" next to the
 * thing they qualify rather than under every cell (2026-09-15). The claim is
 * still the screen's; a test that wants it asks for it the way a reader does.
 */
function hint(label: string): string {
  fireEvent.click(screen.getByLabelText(`${label} 설명`));
  return screen.getByRole('tooltip').textContent ?? '';
}

/**
 * Mount the observe screen on a stored run with the playhead at a chosen point.
 * `at` picks the point from the run's own reel, so a test names what it wants
 * to be looking at (a clock time on the map, or one event's line) rather than a
 * number of seconds.
 */
function observe({ run = detail, log = events, at }: {
  run?: AttemptDetail;
  log?: DomainEvent[];
  at?: { ms: number } | { seq: number };
} = {}) {
  usePlayback.setState({ viewMode: 'researcher', pace: 1, playing: false });
  usePlayback.getState().load({ attemptId: run.attempt.id, detail: run, events: log, village });
  const reel = usePlayback.getState().reel!;
  const rt = !at ? 0 : 'ms' in at ? reel.atTime(at.ms) : reel.atSeq(at.seq);
  usePlayback.setState({ rt, position: reel.locate(rt) });
  return render(
    <ObserveScreen village={village} detail={run} events={log} art={new Set()}
      caseAction={{ label: '새 사례 준비', onClick: noop }}
      onReadEvaluations={noop} />,
  );
}

const hour = (h: number) => ({ ms: h * 3_600_000 });
/** The first event of this type, as a playhead target. */
const first = (type: string, log = events) => ({ seq: log.find((e) => e.type === type)!.seq });

afterEach(cleanup);

describe('ObserveScreen', () => {
  it('shows the village on the map when nothing is being said', () => {
    observe({ at: hour(6) });
    // The map's name is a badge on the map; the synthetic fixture never
    // borrows the real village's name.
    expect(screen.getByText(village.isSynthetic ? '합성 마을' : '은점마을')).toBeDefined();
    // Which ground the map stands on is still stated, behind the gear.
    expect(screen.getByText(new RegExp(village.isSynthetic ? '합성 지도' : '원자료 지형'))).toBeDefined();
    expect(screen.queryByLabelText('MEDial의 판단')).toBeNull();
  });

  it('separates the recording from the run', () => {
    observe();
    // The playback control is a clock over the village day (05:00-22:00) with
    // the residents' review at its end; the loop's own start/pause/stop live in
    // the progress strip, which is not this component.
    expect(screen.getByLabelText('시각')).toBeDefined();
    expect(screen.getByText(/^\d\d:\d\d 주민 평가$/)).toBeDefined();
    expect(screen.getByRole('group', { name: '대사 속도' })).toBeDefined();
    expect(screen.getByLabelText('재생 설정')).toBeDefined();
    expect(screen.getByText('새 사례 준비')).toBeDefined();
    expect(screen.queryByText('실행 중지')).toBeNull();
  });

  it("films a scene with MEDial's judgement where MEDial would stand", () => {
    const accepted = events.find((e) => e.type === 'request.accepted')!;
    observe({ at: { seq: accepted.seq } });
    expect(screen.getByLabelText('MEDial의 판단')).toBeDefined();
    for (const step of ['지금 아는 것', '걸린 규칙', '그래서 이렇게 말한다']) expect(screen.getByText(step)).toBeDefined();
    // The words on screen are the ones the log carries - in the bubble, and
    // again in the panel as what MEDial heard.
    expect(screen.getAllByText(String(accepted.payload.utterance)).length).toBeGreaterThan(0);
  });

  it('never prints a raw event type or a world-only reason', () => {
    for (const at of [first('contact.no_response'), first('task.check_performed'), hour(12)]) {
      const { container } = observe({ at });
      const text = container.textContent ?? '';
      expect(text).not.toContain('undefined');
      expect(text).not.toContain('[object Object]');
      for (const type of ['contact.no_response', 'medial.decided', 'need.resolved', 'world.']) {
        expect(text).not.toContain(type);
      }
      const worldReasons = events
        .filter((e) => e.type === 'world.reachability_resolved')
        .map((e) => String((e.payload as Record<string, unknown>).worldReason ?? ''))
        .filter(Boolean);
      for (const reason of worldReasons) expect(text).not.toContain(reason);
      cleanup();
    }
  });

  it('captions an act that had no words instead of inventing speech', () => {
    const silent = events.find((e) => e.type === 'task.check_performed')!;
    observe({ at: { seq: silent.seq } });
    expect(screen.getByText(sentenceFor(silent)!.text)).toBeDefined();
  });

  it('says where MEDial is not, and what it is waiting for', () => {
    const visit = events.find((e) => e.type === 'task.check_performed')!;
    observe({ at: { seq: visit.seq } });
    expect(screen.getByText('MEDial은 이 장면을 보지 못합니다')).toBeDefined();
    expect(screen.getByText(/확인 결과 대기 중$/)).toBeDefined();
  });

  it('shows each person asked and the sentence they refused with', () => {
    const refusals = neighbours.metrics.refusals!.rows;
    expect(refusals.length).toBeGreaterThan(0);
    const lastRefusal = neighbourEvents.filter((e) => e.type === 'request.declined').pop()!;
    observe({ run: neighbours, log: neighbourEvents, at: { seq: lastRefusal.seq } });
    // The sentence the person gave is on screen; the rule key is not.
    for (const row of refusals.filter((r) => r.seenByMedial)) {
      expect(screen.getAllByText(row.reason!).length).toBeGreaterThan(0);
    }
    expect(screen.queryByText('persona_condition')).toBeNull();
  });

  it('names the day the run took place on, and lists its edits behind a tooltip', () => {
    observe();
    const day = detail.metrics.dayRealization!;
    const tag = screen.getByText(
      { source_baseline: '기록된 하루 그대로', source_jittered: '기록된 시각이 조금 다른 하루',
        plausible_extension: '외출 하나가 다른 하루' }[day.classification],
    );
    // One line per edit, plus one per person deliberately left alone.
    const lines = dayChangeLines(day);
    if (lines.length > 0) expect(tag.getAttribute('title')?.split('\n')).toEqual(lines);
  });
});

describe('CompareScreen', () => {
  function compare(overrides: Partial<Parameters<typeof CompareScreen>[0]> = {}) {
    const ordered = [...session.generations].sort((a, b) => a.index - b.index);
    const right = [...ordered].reverse().find((g) => g.parentGenerationId) ?? ordered[0];
    return render(
      <CompareScreen
        detail={session}
        comparison={null}
        leftId={right.parentGenerationId ?? ordered[0].id}
        rightId={right.id}
        busy={false}
        onSetSides={noop}
        onOpenScene={noop}
        decisions={decisions}
        onOpenAllAttempts={noop}
        onReadEvaluations={noop}
        {...overrides}
      />,
    );
  }

  it('renders the comparison and its question', () => {
    compare();
    expect(screen.getByText('무엇이 달라졌나요?')).toBeDefined();
    expect(screen.getByText('다음 시도에서 바꾼 이유')).toBeDefined();
  });

  it('shows no combined score and no winner', () => {
    const { container } = compare();
    const text = container.textContent ?? '';
    // No aggregate satisfaction, no invented percentage, no trophy. (Plain
    // "점" is not searched for: 은점마을 contains it.)
    expect(text).not.toMatch(/만족도\s*[0-9]/);
    expect(text).not.toMatch(/[0-9]\s*점/);
    expect(text).not.toMatch(/종합\s*점수/);
    expect(text).not.toContain('최고안');
    expect(text).not.toContain('승자');
  });

  it('states the measure mixes helper and helped rather than claiming burden', () => {
    // residentBurden counts the diverted minutes of the person being helped as
    // well as the neighbour's. The row must not assert a distinction the metric
    // does not make.
    compare();
    expect(screen.getByText('누구의 일과가 바뀌었나')).toBeDefined();
    expect(hint('누구의 일과가 바뀌었나')).toMatch(/둘을 구분하지 않습니다/);
  });

  it('labels a pair with no parent relationship as not a controlled comparison', () => {
    const ordered = [...session.generations].sort((a, b) => a.index - b.index);
    const branches = ordered.filter((g) => g.outcome === 'blocked');
    if (branches.length < 2) return; // this fixture has no two unrelated branches
    compare({ leftId: branches[0].id, rightId: branches[1].id });
    expect(screen.getByText('통제 비교가 아닙니다')).toBeDefined();
  });

  it('says which day each side ran on, and who refused, without a score', () => {
    const { container } = compare();
    const text = container.textContent ?? '';
    expect(text).toContain('어느 하루였나');
    expect(text).toContain('누가 거절했나');
    expect(text).not.toContain('persona_condition');
  });

  it('keeps 미수집 distinct from zero', () => {
    const { container } = compare();
    const text = container.textContent ?? '';
    // Whatever this fixture measured, nothing may be silently filled with 0:
    // the word for "not measured" is the one the table uses.
    if (text.includes('미수집')) {
      expect(text).toContain('미수집');
    }
    expect(text).not.toContain('NaN');
  });

  it('offers the field-review choice only as a selection, never as adoption', () => {
    compare();
    const button = screen.queryByText('현장에서 검토할 안 선택');
    if (button) {
      expect(hint('현장 검토 선택')).toMatch(/서비스 도입 승인이 아닙니다/);
    }
  });
});

describe('EvaluationsScreen', () => {
  function evaluations(overrides: Partial<Parameters<typeof EvaluationsScreen>[0]> = {}) {
    const ordered = [...session.generations].sort((a, b) => a.index - b.index);
    return render(
      <EvaluationsScreen
        detail={session}
        generation={ordered[0]}
        personas={personas}
        onSelectGeneration={noop}
        onOpenScene={noop}
        onGoToImprove={noop}
        {...overrides}
      />,
    );
  }

  it('reads one resident in doc 20 order and calls the evaluation simulated', () => {
    const { container } = evaluations();
    const text = container.textContent ?? '';
    expect(text).toContain('모의 주민 평가');
    expect(text).toContain('1 · 이번에 무엇을 경험했나');
    expect(text).toContain('2 · 차원별 평가와 이유');
    expect(text).toContain('4 · 판단할 수 없는 것');
    // The four dimension assessments are said in Korean, never as their keys.
    expect(text).not.toContain('help_resolution');
    expect(text).not.toMatch(/\bmixed\b/);
  });

  it('counts items and says so, rather than showing a score', () => {
    const { container } = evaluations();
    const text = container.textContent ?? '';
    expect(text).toContain('평가 항목의 개수');
    expect(text).not.toMatch(/만족도\s*[0-9]/);
    expect(text).not.toContain('평균');
    expect(text).not.toContain('승자');
  });

  it('keeps 미경험 out of the complaints and says it is an observation', () => {
    evaluations();
    expect(hint('읽는 순서')).toContain('미경험과 제안 없음은 불만이 아니므로');
  });

  it('opens an evaluation item\'s evidence in place and closes back to it', () => {
    const ordered = [...session.generations].sort((a, b) => a.index - b.index);
    const review = ordered[0].reviews.find((r) =>
      r.items.some((i) => i.eventRefs.length > 0),
    );
    if (!review) return;
    evaluations();
    // The person list is the left column; the same name also appears in the
    // opened card, so the click target is the list row.
    fireEvent.click(screen.getAllByText(new RegExp(`^${review.actorId}$`))[0]);
    const open = screen.getAllByText(/사건 근거 [0-9]+건 보기/)[0];
    fireEvent.click(open);
    expect(screen.getAllByText('그 장면 열기').length).toBeGreaterThan(0);
    fireEvent.click(screen.getAllByText(/사건 근거 [0-9]+건 닫기/)[0]);
    expect(screen.queryByText('그 장면 열기')).toBeNull();
  });

  it('shows the original evaluation items an issue was made of', () => {
    const ordered = [...session.generations].sort((a, b) => a.index - b.index);
    if ((ordered[0].synthesis?.issueGroups.length ?? 0) === 0) return;
    const { container } = evaluations();
    expect(container.textContent).toContain('원본 평가');
  });
});

describe('ChangeComposer, through the improve screen', () => {
  /** The fixture ends after its one pair, so authoring is re-enabled here to
   *  exercise the composer; the flag is the server's own. */
  const authoring: SessionDetail = { ...session, canAuthor: true };

  function improve(overrides: Partial<Parameters<typeof CompareScreen>[0]> = {}) {
    const ordered = [...authoring.generations].sort((a, b) => a.index - b.index);
    const right = [...ordered].reverse().find((g) => g.parentGenerationId) ?? ordered[0];
    return render(
      <CompareScreen
        detail={authoring}
        comparison={null}
        leftId={right.parentGenerationId ?? ordered[0].id}
        rightId={right.id}
        busy={false}
        onSetSides={noop}
        onOpenScene={noop}
        decisions={decisions}
        onOpenAllAttempts={noop}
        onReadEvaluations={noop}
        {...overrides}
      />,
    );
  }

  it('offers authoring from the rule catalogue with no draft in hand', () => {
    improve();
    expect(screen.getByText('지원 규칙에서 직접 작성')).toBeDefined();
    fireEvent.click(screen.getByText('지원 규칙에서 직접 작성'));
    // Typed controls, generated from the server's catalogue.
    expect(screen.getByText('어떤 규칙을 바꾸나요')).toBeDefined();
    expect(screen.getByText('바뀌기 전')).toBeDefined();
  });

  it('has no free-text field for the rule sentence and no binding input', () => {
    improve();
    fireEvent.click(screen.getByText('지원 규칙에서 직접 작성'));
    const text = document.body.textContent ?? '';
    expect(text).not.toContain('변경 후 Quest/Task 규칙');
    expect(text).not.toContain('내부 실행값 수정');
    expect(hint('이유')).toContain('글로 적은 내용이 실행을 바꾸지 않습니다');
  });

  it('keeps the input and shows the reason when a save is refused', async () => {
    improve({ decisions: { ...decisions,
                         onSaveResearcherChangeSet: async () => '재연락 횟수는 0-6 사이여야 한다.' } });
    fireEvent.click(screen.getByText('지원 규칙에서 직접 작성'));
    const nameBox = screen.getByText('이 수정안의 이름').querySelector('input')!;
    fireEvent.change(nameBox, { target: { value: '내가 쓴 이름' } });
    const why = screen.getByLabelText('변경을 시도하는 이유');
    fireEvent.change(why, { target: { value: '본인 확인 기회를 한 번 더 준다' } });
    fireEvent.click(screen.getByText('수정안으로 저장 (실행하지 않음)'));
    await screen.findByText('재연락 횟수는 0-6 사이여야 한다.');
    expect(screen.getByText(/입력은 그대로 두었습니다/)).toBeDefined();
    expect((nameBox as HTMLInputElement).value).toBe('내가 쓴 이름');
  });

  it('offers "이번에는 수정하지 않음" as an explicit end that needs a reason', () => {
    improve();
    fireEvent.click(screen.getByText('이번에는 수정하지 않음'));
    const button = screen.getByText('수정하지 않기로 기록') as HTMLButtonElement;
    expect(button.disabled).toBe(true);
  });

  it('decides nothing in the sim version, and says why', () => {
    improve({ decisions: null });
    expect(screen.getByText('미리 돌려 둔 기록입니다.')).toBeDefined();
    expect(screen.queryByText('지원 규칙에서 직접 작성')).toBeNull();
    expect(screen.queryByText('이번에는 수정하지 않음')).toBeNull();
    expect(screen.queryByText('현장에서 검토할 안 선택')).toBeNull();
    expect(screen.queryByText('지금까지의 결정 기록 보기')).toBeNull();
  });

  it('tells "the rule ran" apart from "there was no difference"', () => {
    const { container } = improve();
    const text = container.textContent ?? '';
    expect(text).toContain('바뀐 규칙이 실행됐나');
    expect(hint('바뀐 규칙이 실행됐나')).toContain(
      '지원됨 · 적용 상황이 생김 · 실제로 그 분기를 지남',
    );
  });
});

describe('RecordingsScreen', () => {
  const row = session.session;

  it('lists what the real version ran, and says how each was made', () => {
    render(<RecordingsScreen sessions={[row]} currentId={null} onOpen={noop} onReturn={noop} />);
    expect(screen.getByRole('list', { name: '미리 돌려 둔 기록' })).toBeDefined();
    expect(screen.getByText(row.label)).toBeDefined();
    expect(screen.getByText(madeBy(row))).toBeDefined();
    expect(screen.getByText('이 기록 보기')).toBeDefined();
  });

  it('tells a rule-made recording from a model-made one', () => {
    const llm = { behaviourAdapter: 'llm', institutionAdapter: 'llm',
                  reviewAdapter: 'llm', improvementAdapter: 'llm' };
    expect(madeBy({ ...row, ...llm })).toBe('모델로 생성');
    expect(madeBy({ ...row, ...llm, behaviourAdapter: 'rule' })).toBe('일부 모델로 생성');
    expect(madeBy({ ...row, behaviourAdapter: 'rule', institutionAdapter: 'rule',
                    reviewAdapter: 'rule', improvementAdapter: 'rule' })).toBe('규칙으로 계산');
  });

  it('marks a recording that stopped before its evaluations', () => {
    expect(stoppedEarly({ ...row, status: 'failed' })).toBe('중간에 멈춘 기록');
    expect(stoppedEarly(row)).toBeNull();
  });

  it('says how to make recordings when there are none', () => {
    render(<RecordingsScreen sessions={[]} currentId={null} onOpen={noop} onReturn={noop} />);
    expect(screen.getByText('아직 얼려 둔 기록이 없습니다.')).toBeDefined();
    expect(screen.getByText('python scripts/freeze_sim.py')).toBeDefined();
  });
});
