import { cleanup, render, screen, within } from '@testing-library/react';
import { afterEach, describe, expect, it } from 'vitest';
import attemptFixture from '../../../../fixtures/ui/attempt.json';
import neighboursFixture from '../../../../fixtures/ui/attempt-neighbours.json';
import eventsFixture from '../../../../fixtures/ui/events.json';
import neighbourEventsFixture from '../../../../fixtures/ui/events-neighbours.json';
import personasFixture from '../../../../fixtures/ui/personas.json';
import sessionFixture from '../../../../fixtures/ui/session.json';
import villageFixture from '../../../../fixtures/ui/village.json';
import type { GenerationDetail, SessionDetail } from '../api/iteration';
import type { AttemptDetail, DomainEvent, PersonasPayload, VillagePayload } from '../api/types';
import { medialKnowledge, posesAt } from '../positions';
import { dayChangeLines } from '../selectors/words';
import { eventsUpTo } from '../store';
import CompareScreen from './CompareScreen';
import ObserveScreen from './ObserveScreen';

// Mounting the two data-heavy screens against real API payloads built from the
// SYNTHETIC village (fixtures/ui/, regenerated by scripts/gen_ui_fixtures.py).
//
// Synthetic on purpose: these files are committed, and the source-derived
// registry lives in the gitignored local-data/ precisely so that real place
// names, ages and jobs never enter the repository. The payload *shapes* are
// identical, which is what the screens are being tested against.
//
// The point is not pixels. It is that a screen which throws on real data, or
// which quietly prints "undefined" or an internal event name where a sentence
// belongs, is otherwise invisible: `tsc` cannot see it and this repository has
// no browser in CI. So each assertion below is a claim the screen makes about
// the run - never a restatement of a stylesheet.

const village = villageFixture as unknown as VillagePayload;
const detail = attemptFixture as unknown as AttemptDetail;
const events = (eventsFixture as { events: DomainEvent[] }).events;
/** The same day under 가까운 이웃 우선, where the refusal table actually fires. */
const neighbours = neighboursFixture as unknown as AttemptDetail;
const neighbourEvents = (neighbourEventsFixture as { events: DomainEvent[] }).events;
const personas = personasFixture as unknown as PersonasPayload;
const session = sessionFixture as unknown as SessionDetail;

const noop = () => {};

/** Late in the day, so the log has something in every stage. */
const CURSOR = events.length;

function observe(overrides: Partial<Parameters<typeof ObserveScreen>[0]> = {}) {
  const visible = eventsUpTo(events, CURSOR, 'researcher');
  const generation: GenerationDetail | null =
    [...session.generations].sort((a, b) => a.index - b.index)[0] ?? null;
  return render(
    <ObserveScreen
      village={village}
      detail={detail}
      poses={posesAt(detail.timeline ?? null, 12 * 60 * 60 * 1000)}
      visibleEvents={visible}
      allEvents={events}
      medialKnown={medialKnowledge(events, CURSOR)}
      reservations={[]}
      viewMode="researcher"
      cursorSeq={CURSOR}
      eventCount={detail.attempt.eventCount}
      atMs={12 * 60 * 60 * 1000}
      playing={false}
      selectedCluster={null}
      selectedActor={null}
      detailActor="P1"
      personas={personas}
      generation={generation}
      onSetViewMode={noop}
      onSelectCluster={noop}
      onOpenDetail={noop}
      onPlay={noop}
      onPause={noop}
      onSeek={noop}
      onStep={noop}
      onStepBack={noop}
      onRestart={noop}
      onOpenScene={noop}
      {...overrides}
    />,
  );
}

afterEach(cleanup);

describe('ObserveScreen', () => {
  it('renders all three columns from real payloads', () => {
    observe();
    expect(screen.getByText('은점마을')).toBeDefined();
    expect(screen.getByText('MEDial · 조율 현황')).toBeDefined();
    // The person column is headed by whoever is being shown, not by a title.
    expect(screen.getByLabelText('볼 사람')).toBeDefined();
    // The map says which kind of ground it is standing on, always.
    expect(screen.getByText(village.isSynthetic ? '합성 지도' : '원자료 지형')).toBeDefined();
  });

  it('separates the recording from the run', () => {
    observe();
    // The playback control says it is playing back a recording; the loop's own
    // start/pause/stop live in the progress strip, which is not this component.
    expect(screen.getByText(/기록 재생/)).toBeDefined();
    expect(screen.queryByText('실행 중지')).toBeNull();
    expect(screen.queryByText('실행 일시정지')).toBeNull();
  });

  it('never prints a raw event type where a sentence belongs', () => {
    const { container } = observe();
    const text = container.textContent ?? '';
    expect(text).not.toContain('undefined');
    expect(text).not.toContain('[object Object]');
    for (const type of ['contact.no_response', 'medial.decided', 'need.resolved']) {
      // The type may appear inside a folded technical list; it must not appear
      // in the readable narration, which is what the summary lines are.
      const summaries = Array.from(container.querySelectorAll('button[title]'))
        .map((node) => node.textContent ?? '')
        .join(' ');
      expect(summaries).not.toContain(type);
    }
  });

  it('does not narrate the world-only reason a call went unanswered', () => {
    const { container } = observe();
    const text = container.textContent ?? '';
    // The type name is allowed inside the folded technical list and in the
    // sentence that explains why it is excluded; what must never appear is the
    // world's *reason*, which the caller does not have.
    const narration = Array.from(container.querySelectorAll('button[title]'))
      .map((node) => node.textContent ?? '')
      .join(' ');
    expect(narration).not.toContain('world.');
    // Whatever the deck's worldReason says, the caller cannot know it.
    const worldReasons = events
      .filter((e) => e.type === 'world.reachability_resolved')
      .map((e) => String((e.payload as Record<string, unknown>).worldReason ?? ''))
      .filter(Boolean);
    for (const reason of worldReasons) expect(text).not.toContain(reason);
  });

  it('shows each person asked and the sentence they refused with', () => {
    const cursor = neighbourEvents.length;
    observe({
      detail: neighbours,
      visibleEvents: eventsUpTo(neighbourEvents, cursor, 'researcher'),
      allEvents: neighbourEvents,
      cursorSeq: cursor,
      eventCount: neighbours.attempt.eventCount,
      detailActor: null,
    });
    expect(screen.getByText('누구에게 부탁했고, 뭐라고 했나')).toBeDefined();
    const refusals = neighbours.metrics.refusals!.rows;
    expect(refusals.length).toBeGreaterThan(0);
    // The sentence the person gave is on screen; the rule key is not.
    for (const row of refusals) {
      expect(screen.getAllByText(row.reason!).length).toBeGreaterThan(0);
    }
    expect(screen.queryByText('persona_condition')).toBeNull();
    // Nothing here was hidden from MEDial, so nothing says so.
    expect(screen.queryByText('MEDial은 모름')).toBeNull();
  });

  it('names the day the run took place on, and lists its edits behind a tooltip', () => {
    observe();
    const day = detail.metrics.dayRealization!;
    const tag = screen.getByText(
      { source_baseline: '기록된 하루 그대로', source_jittered: '기록된 시각이 조금 다른 하루',
        plausible_extension: '외출 하나가 다른 하루' }[day.classification],
    );
    // One line per edit, plus one per person deliberately left alone.
    const lines = dayChangeLines(day);
    if (lines.length > 0) expect(tag.getAttribute('title')?.split('\n')).toEqual(lines);
  });

  it('rests on the board of everyone, and does not claim a person nobody chose', () => {
    observe({ detailActor: null });
    expect(screen.getByText('마을 사람들')).toBeDefined();
    // Everyone with a timeline is on it, named the way every panel names them.
    for (const id of Object.keys(detail.timeline?.actors ?? {})) {
      expect(screen.getAllByText(id === 'P6' ? '이장' : id).length).toBeGreaterThan(0);
    }
    // The person view is not open, so its controls are absent - the column used
    // to fall back to whoever sorted first and present them as the subject.
    expect(screen.queryByLabelText('볼 사람')).toBeNull();
  });

  it('opens one person over the board, with a way back', () => {
    observe({ detailActor: 'P1' });
    expect(screen.getByLabelText('볼 사람')).toBeDefined();
    expect(screen.getByTitle('마을 사람들로 돌아가기')).toBeDefined();
    expect(screen.queryByText('마을 사람들')).toBeNull();
  });

  it('counts only what happened at or before the cursor', () => {
    // The board's per-person number is a count of events up to the cursor, so
    // at the start of the day there is nothing to count. A whole-day total here
    // would show the reader the end of a day they are watching from 08:00.
    const { container } = observe({ detailActor: null, cursorSeq: 0, visibleEvents: [] });
    expect(container.textContent).toContain('만족도 점수가');
  });

  it('shows the person column for the selected resident, with their own day', () => {
    observe({ detailActor: 'P1' });
    expect(screen.getAllByText(/P1/).length).toBeGreaterThan(0);
    // The satisfaction section is present and says what it is, without a score.
    expect(screen.getByText('하루를 마친 뒤의 평가')).toBeDefined();
    expect(screen.getByText(/점수가 아니고/)).toBeDefined();
  });

  it('says plainly when there is no recorded speech rather than inventing some', () => {
    // P10 is at home all day in this deck and is spoken to by nobody.
    observe({ detailActor: 'P10' });
    expect(screen.getByText('주고받은 말')).toBeDefined();
    expect(screen.getByText(/없는 대화를 만들지 않습니다/)).toBeDefined();
  });
});

describe('CompareScreen', () => {
  function compare(overrides: Partial<Parameters<typeof CompareScreen>[0]> = {}) {
    const ordered = [...session.generations].sort((a, b) => a.index - b.index);
    const right = [...ordered].reverse().find((g) => g.parentGenerationId) ?? ordered[0];
    return render(
      <CompareScreen
        detail={session}
        comparison={null}
        leftId={right.parentGenerationId ?? ordered[0].id}
        rightId={right.id}
        busy={false}
        onSetSides={noop}
        onOpenScene={noop}
        onConfirmChangeSet={noop}
        onSaveResearcherChangeSet={noop}
        onOpenFieldSheet={noop}
        onOpenAllAttempts={noop}
        decisionReason=""
        onDecisionReason={noop}
        {...overrides}
      />,
    );
  }

  it('renders the comparison and its question', () => {
    compare();
    expect(screen.getByText('무엇이 달라졌나요?')).toBeDefined();
    expect(screen.getByText('다음 시도에서 바꾼 이유')).toBeDefined();
  });

  it('shows no combined score and no winner', () => {
    const { container } = compare();
    const text = container.textContent ?? '';
    // No aggregate satisfaction, no invented percentage, no trophy. (Plain
    // "점" is not searched for: 은점마을 contains it.)
    expect(text).not.toMatch(/만족도\s*[0-9]/);
    expect(text).not.toMatch(/[0-9]\s*점/);
    expect(text).not.toMatch(/종합\s*점수/);
    expect(text).not.toContain('최고안');
    expect(text).not.toContain('승자');
  });

  it('states the measure mixes helper and helped rather than claiming burden', () => {
    // residentBurden counts the diverted minutes of the person being helped as
    // well as the neighbour's. The row must not assert a distinction the metric
    // does not make.
    compare();
    expect(screen.getByText('누구의 일과가 바뀌었나')).toBeDefined();
    // One caveat per column, so both sides carry it.
    expect(screen.getAllByText(/둘을 구분하지 않습니다/).length).toBeGreaterThan(0);
  });

  it('labels a pair with no parent relationship as not a controlled comparison', () => {
    const ordered = [...session.generations].sort((a, b) => a.index - b.index);
    const branches = ordered.filter((g) => g.outcome === 'blocked');
    if (branches.length < 2) return; // this fixture has no two unrelated branches
    compare({ leftId: branches[0].id, rightId: branches[1].id });
    expect(screen.getByText('통제 비교가 아닙니다')).toBeDefined();
  });

  it('says which day each side ran on, and who refused, without a score', () => {
    const { container } = compare();
    const text = container.textContent ?? '';
    expect(text).toContain('어느 하루였나');
    expect(text).toContain('누가 거절했나');
    expect(text).not.toContain('persona_condition');
  });

  it('keeps 미수집 distinct from zero', () => {
    const { container } = compare();
    const text = container.textContent ?? '';
    // Whatever this fixture measured, nothing may be silently filled with 0:
    // the word for "not measured" is the one the table uses.
    if (text.includes('미수집')) {
      expect(text).toContain('미수집');
    }
    expect(text).not.toContain('NaN');
  });

  it('offers the field-review choice only as a selection, never as adoption', () => {
    compare();
    const button = screen.queryByText('현장에서 검토할 안 선택');
    if (button) {
      const region = button.closest('div')!;
      expect(within(region).getByText(/서비스 도입 승인이 아닙니다/)).toBeDefined();
    }
  });
});
